networks:
  appName:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: appServer
    ports:
      - '8088:80'
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mariadb
    networks:
      - appName
  mariadb:
    image: mariadb:10.11
    container_name: appDb
    restart: unless-stopped
    tty: true
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: appName
      MYSQL_USER: nelwhix
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    networks:
      - appName

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: appPhp
    volumes:
      - ./app:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - appName