version: '3'

networks:
  appName:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: appserver
    ports:
      - '8088:80'
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - appName

  mysql:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: appName
      MYSQL_USER: nelwhix
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - appName

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php-fpm
    volumes:
      - ./app:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - appName
  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html
    networks:
      - appName